(add-to-list 'load-path "~/.emacs.d/elisp")

(load "init-packages.el")
(load "init-appearance.el")
(load "init-backups.el")
(load "init-magit.el")
(load "init-eshell.el")
(load "init-newline.el")
(load "init-yasnippet.el")
(load "init-delete.el")
